apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: fastendp-deployment
spec:
  template:
    metadata:
      name: fastendp-pod
      labels:
        app: webscout
        type: fastendp
    spec:
      containers:
        - name: fastendp-con
          image: ehsanu/webscout-endpoint
          ports:
            - containerPort: 8000
        # - name: redis-front-con
        #   image: redis
        #   ports:
        #     - containerPort: 6379
        # - name: mongo-con
        #   image: mongo
        #   ports:
        #     - containerPort: 27017
        #   env:
        #     - name: MONGO_INITDB_ROOT_USERNAME
        #       value: root
        #     - name: MONGO_INITDB_ROOT_PASSWORD
        #       value: toor
  replicas: 1
  selector:
    matchLabels:
      app: webscout
      type: fastendp