apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: webscout
        type: frontend
    spec:
      containers:
        - name: frontend-con
          image: ehsanu/webscout-frontend
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: webscout
      type: frontend