apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-deployment
spec:
  template:
    metadata:
      name: mongo-pod
      labels:
        app: webscout
        type: db
    spec:
      containers:
        - name: mongo-con
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: toor
  replicas: 1
  selector:
    matchLabels:
      app: webscout
      type: db