version: "3.8"


services:
    
  endpoint:
    image: ehsanu/endpoint:1.0
    networks:
      webscout_network:
        aliases:
          - endpoint
    depends_on:
      - frontier
      - resq
      - db
    ports:
      - 5000:5000
  
  frontier:
    image: redis
    networks:
      webscout_network:
        aliases:
          - frontier
    ports:
      - 6379:6379

  resq:
    image: redis
    networks:
      webscout_network:
        aliases:
          - resq
    ports:
      - 6380:6379
  
  db:
    image: mongo
    networks:
      webscout_network:
        aliases:
          - db
    ports:
      - 27017:27017

  worker:
    image: ehsanu/worker:1.0
    networks:
      - webscout_network
    depends_on:
      - frontier
      - db
      - resq


  controller:
    image: ehsanu/controller:1.0
    networks:
      - webscout_network
    depends_on:
      - db

networks:
  webscout_network: