version: "3.8"


services:
  frontend:
    image: ehsanu/webscout-frontend
    ports:
      - 80:80
    networks:
      webscout_network:
        aliases:
          - frontend
    depends_on:
      - fastendp
    
  fastendp:
    image: ehsanu/webscout-endpoint
    networks:
      webscout_network:
        aliases:
          - fastendp
    depends_on:
      - redisfront
      - redisback
      - fingers
  
  redisfront:
    image: redis
    networks:
      webscout_network:
        aliases:
          - redisfront

  redisback:
    image: redis
    networks:
      webscout_network:
        aliases:
          - redisback
  
  fingers:
    image: mongo:4.4
    networks:
      webscout_network:
        aliases:
          - fingers

  scrapyworker:
    image: ehsanu/webscout-scrapy-worker
    networks:
      - webscout_network
    depends_on:
      - redisback
      - fingers
      - redisfront

networks:
  webscout_network: