version: "3.8"


services:
    
  endpoint:
    image: ehsanu/endpoint:1.0
    networks:
      webscout_network:
        aliases:
          - endpoint
    depends_on:
      - frontier
      - resq
      - db
  
  frontier:
    image: redis
    networks:
      webscout_network:
        aliases:
          - frontier

  resq:
    image: redis
    networks:
      webscout_network:
        aliases:
          - resq
  
  db:
    image: mongo
    networks:
      webscout_network:
        aliases:
          - db

  worker:
    image: ehsanu/worker:1.0
    networks:
      - webscout_network
    depends_on:
      - frontier
      - db
      - resq

  controller:
    image: ehsanu/controller:1.0
    networks:
      - webscout_network
    depends_on:
      - db

networks:
  webscout_network: