version: "3.8"


services:
    
  endpoint:
    image: ehsanu/webscout-endpoint
    networks:
      webscout_network:
        aliases:
          - endpoint
    depends_on:
      - frontier
      - resq
      - webscoutdb
  
  frontier:
    image: redis
    networks:
      webscout_network:
        aliases:
          - frontier

  resq:
    image: redis
    networks:
      webscout_network:
        aliases:
          - resq
  
  webscoutdb:
    image: mongo
    networks:
      webscout_network:
        aliases:
          - webscoutdb

  worker:
    image: ehsanu/webscout-scrapy-worker
    networks:
      - webscout_network
    depends_on:
      - frontier
      - webscoutdb
      - resq

networks:
  webscout_network: