apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: webscout
        type: db
    spec:
      containers:
        - name: db-con
          image: mongo
          ports:
            - containerPort: 27017
  replicas: 1
  selector:
    matchLabels:
      app: webscout
      type: db