apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  template:
    metadata:
     name: monitoring-pod
     labels:
       app: webscout
       type: monitoring
    spec:
     containers:
       - name: monitoring-con
         image: ehsanu/controller:1.0
         volumeMounts:
           - mountPath: /etc/webscout
             name: config-vol
     volumes:
       - name: config-vol
         configMap:
           name: webscout-config
  replicas: 1
  selector:
    matchLabels:
      app: webscout
      type: monitoring
