apiVersion: v1
kind: Service 
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    app: webscout
    type: frontend