apiVersion: v1
kind: Service
metadata:
  name: redisfront-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379 
  selector:
    app: webscout
    type: starturls

















 
























