apiVersion: v1
kind: Service 
metadata:
  name: endpoint
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30002
  selector:
    app: webscout
    name: webscout-endpoint-pod