apiVersion: v1
kind: Pod
metadata:
  name: frontier-pod
  labels:
    app: webscout
    type: frontier
spec:
  containers:
    - name: frontier-con
      image: redis
      ports:
        - containerPort: 6379